### ISSUE TITLE
Al iniciar sesión el usuario NO debería ver el botón de registrarse

### ISSUE THREAD

**Issue by geronm12** [Luchoab/proyectoFinal#2]
### SITUACION ACTUAL
Cuando un usuario inicia sesión puede continuar viendo el botón de registrarse

![image](https://user-images.githubusercontent.com/44532299/233118361-87318608-b35c-4d4f-aa6e-64f76eb08e38.png)

### PASOS PARA REPRODUCIR

Abrir el proyecto, click en iniciar sesión. Una vez loggeado se puede observar que el botón de registrarse permanece. 

### POSIBLE SOLUCION

Utilizar renderizado condicional para no mostrar el botón si el usuario está loggeado

**Credenciales Necesarias
User: admin@role
password: admin**

**Comment by aleli-b** [comment]
Hecho! El boton de registro ya no aparece si hay un usuario activo

**Comment by geronm12** [comment]
Revisado, esto está ok. Cierro el issue.
