### ISSUE TITLE
Al eliminar un registro se debería mostrar un pop up para mejorar la UX

### ISSUE THREAD

**Issue by geronm12** [Luchoab/proyectoFinal#3]
### SITACION ACTUAL

Loggeado como usuario administrador, dirigirse a la solapa de Productos, seleccionar un producto y hacer click en el tacho de basura. El producto automáticamente desaparecerá de la lista.

https://user-images.githubusercontent.com/44532299/233120011-6164211b-11e7-4180-a6d3-3f6c91e0da36.mp4

### SITUACION ESPERADA

Se debería mostrar un cartel de decisión para permitirle al usuario tener margen de error. Si no, el usuario podría eliminar cosas importantes sin querer.

### POSIBLE FIX

Utilizar un pop up parecido al que se utiliza para modificar/agregar, y pasarle como funcion onClick al botón del pop up la lógica
de eliminación del producto (el servicio/método que utilicen), en caso de que el usuario haga click en cancelar no pasará nada y el usuario tendrá tiempo de decidir si realmente desea eliminar ese elemento o no.

**Comment by aleli-b** [comment]
Hecho, añadidas confirm alerts en las tres paginas de admin antes de eliminar elementos

**Comment by geronm12** [comment]
Perfecto, ahora si. Cierro el issue.
