### ISSUE TITLE
Al navegar a "Mis pedidos" me lleva al carrito

### ISSUE THREAD

**Issue by geronm12** [Luchoab/proyectoFinal#4]
### SITACION ACTUAL

Loggeado como un usuario con posibilidad de acceder a la opción "Mis Pedidos", hacer click en la misma, nos dirigirá a la pantalla del carrito de compras.

https://user-images.githubusercontent.com/44532299/233121411-4d100018-58f2-4e27-b684-c0166ae6d21e.mp4

### SITUACION ESPERADA

El link de "Mis Pedidos" debería redireccionarme a que yo pueda ver todos los pedidos que hice 

### POSIBLE FIX
Si tienen hecha la página de mis pedidos con cambiar la ruta debería ser suficiente, en caso de que no tengan la página, no hace falta que solucionen este error.

**Comment by aleli-b** [comment]
No está hecha la página, por eso pusimos que mande al carrito, de igual manera si es preferible lo mandamos a un er404

**Comment by geronm12** [comment]
Sii es mejor si la mandan a un error 404 para que el usuario distinga mejor. Lo cierro al issue igual
