### ISSUE TITLE
Mejorar mensajes de error y mensajes al agregar/modificar un producto

### ISSUE THREAD

**Issue by geronm12** [Luchoab/proyectoFinal#5]
### SITUACION ACTUAL

1 ) Loggeado como un usuario administrador, al intentar agregar o modificar un producto, se pueden ver una serie de mensajes que dicen "Error en" que no se quitan hasta que el texto llega a cierta longitud (info, descripcion).  

![image](https://user-images.githubusercontent.com/44532299/233122488-389359b8-181e-496c-8d6b-4501c4354063.png)

2) Loggeado como un usuario administrador modificar o agregar un producto, luego del mensaje de felicitaciones el pop up no se cierra y el formulario no se limpia.

https://user-images.githubusercontent.com/44532299/233122785-5700ff67-7dc9-48e8-ab4b-4db7542da4a6.mp4

3) Loggeado como usuario administrador al modificar un producto su mensaje de felicitaciones dice "Agregar"

![image](https://user-images.githubusercontent.com/44532299/233122678-40f5d9bc-9aa4-4fa1-8be0-7245e394e6ce.png)

NOTA: En el video, además, pueden observar todos los bugs mencionados anteriormente.

### SITUACION ESPERADA

1) Los mensajes de error  deberían ser más específicos para indicarle al usuario como solucionar los distintos errores para poder enviar el formulario. En el caso de la info por ejemplo el mensaje debería ser algo así: "Error, la información tiene un mínimo de 50 carácteres"

2) Al finalizar la interacción con el formulario (guardar), luego del mensaje de felicitaciones el mismo debería cerrarse automáticamente para evitar que el usuario intente guardar muchas veces el mismo producto.

3) Los mensajes deben ser acordar a la acción que vamos a realizar, si estamos editando debería decir "Editado con éxito"

### POSIBLE SOLUCION

1) Cambiar los mensajes de error para indicar una forma de solucionar el mismo.
2) Pasar como prop o enviar la función quie se encarga de modificar el estado que muestra el popUp para una vez finalizado el guardado y mostrado el mensaje de felicitaciones ejecutar el setShowPopUp(false); 
3) Cambiar el mensajito de felicitaciones de "Agregado con  éxito" a "Editado o Modificado con éxito"

**Comment by aleli-b** [comment]
gero que tal, mira te comento este problema, pude hacer todo menos dos cosas. No puedo hacer que se limpie el modal en ningun caso, simplemente no encuentro la solucion en ningun lado. Y lo segundo es que en el caso de los forms de editar elementos, que aparecen integrados dentro de un map, al tener la funcion de editar producto en el componente padre no puedo hacer otra cosa que mandarle las funciones de handleclose y show  por props. En el caso del form modal de agregar productos no hay problema, porque no esta metido en un map, entonces el modal funciona como corresponde, ahora en el caso de los modales que estan metidos en maps, al mandar la ejecucion de su handleshow por props sucede que todos los modales de todos los elementos alojados en la base de datos se abren al mismo tiempo. De todas maneras la solucion se cual es, se como arreglarlo, pero requiere una reestructuracion del codigo. Aplique lo que me pediste en el form de agregar productos, si lo queres probar, y si necesitas para la correccion que te cambie el codigo en los otros dos casos en el que esta anidado el modal en un map, entonces decime y me pongo a hacerlo. Gracias y perdon la molestia

**Comment by aleli-b** [comment]
Para responder al issue de forma mas concisa: 1) ya fueron mejorados los mensajes de error en los forms, para que indiquen mas especificamente donde esta el problema en el input, 2) el form ahora se cierra al ser exitoso el uso del mismo (solo en el caso del form de agregar productos), y 3) cambiado el mensaje desubicado en los form de editar elementos jeje

**Comment by geronm12** [comment]
Ale, cómo estás? no te hagas problema. Como consejo tengan cuidado con la generación de los popUps para evitar ese conflicto porque si manejan grandes volumenes de datos puede terminar generar sobrecarga o crashear la app. Ahí revise las cosas y está todo ok. Te lo cierro.
